# 定义Spring应用名称，它是一个微服务的名称，一个微服务可拥有多个实例
spring:
  application:
    name:  eureka-server
  profiles:
    active: peer2


eureka:
  client:
    # 服务自身就是治理中心，所以这里设置为false，取消注册
    register-with-eureka: false
    # 取消服务获取，至于服务获取，本章后续会讨论
    fetch-registry: false
    # 服务注册域地址
    service-url:
     defaultZone: http://192.168.1.100:5002/eureka/,http://192.168.1.100:5001/eureka/
  instance:
    # 服务治理中心服务器IP
    hostname: 192.168.1.100